name       : remake
version    : 4.1
release    : 1
source     :
    - http://sourceforge.net/projects/bashdb/files/remake/4.1+dbg-1.1/remake-4.1+dbg1.1.tar.bz2 : 42eb79a8418e327255341a55ccbdf358eed42c4e15ffb39052c1627de83521fe
license    : GPL-2.0+
component  : programming.tools
summary    : Patched GNU Make with improved error reporting and debugging
description: |
    remake is a patched version of GNU Make that adds improved error reporting, the ability to trace execution in a comprehensible way, and a debugger.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
