name       : remake
version    : '4.3'
release    : 3
source     :
    - https://github.com/rocky/remake/releases/download/release_4.3%2Bdbg-1.5/remake-4.3+dbg-1.5.tar.lz : 7cfabad2f41eebcdd9195c808b879abca2cbd483eefe452dc8a8a6f225d13d55
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Patched GNU Make with improved error reporting and debugging
description: |
    remake is a patched version of GNU Make that adds improved error reporting, the ability to trace execution in a comprehensible way, and a debugger.
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/info
